### ISSUE TITLE
Using fart

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/MediaWiki-Butt-Ruby#4]
```ruby
require_relative 'lib/mediawiki-butt'

butt = MediaWiki::Butt.new("http://ftb.gamepedia.com")
butt.login("ESAEBSAD", "-REDACTED-")

puts butt.get_contrib_count("xbony2", true)
```

results in...

```
/Library/Ruby/Gems/2.0.0/gems/string-utility-2.0.0/lib/utils.rb:3: warning: Refinements are experimental, and the behavior may change in future versions of Ruby!
/Users/xbony2/git/MediaWiki-Butt-Ruby/lib/mediawiki/query.rb:124:in `<module:Lists>': undefined method `using' for MediaWiki::Query::Lists:Module (NoMethodError)
	from /Users/xbony2/git/MediaWiki-Butt-Ruby/lib/mediawiki/query.rb:123:in `<module:Query>'
	from /Users/xbony2/git/MediaWiki-Butt-Ruby/lib/mediawiki/query.rb:5:in `<module:MediaWiki>'
	from /Users/xbony2/git/MediaWiki-Butt-Ruby/lib/mediawiki/query.rb:4:in `<top (required)>'
	from /Users/xbony2/git/MediaWiki-Butt-Ruby/lib/mediawiki/butt.rb:2:in `require_relative'
	from /Users/xbony2/git/MediaWiki-Butt-Ruby/lib/mediawiki/butt.rb:2:in `<top (required)>'
	from /Users/xbony2/git/MediaWiki-Butt-Ruby/lib/mediawiki-butt.rb:1:in `require_relative'
	from /Users/xbony2/git/MediaWiki-Butt-Ruby/lib/mediawiki-butt.rb:1:in `<top (required)>'
	from test.rb:1:in `require_relative'
	from test.rb:1:in `<main>'
```

**Comment by xbony2** [comment]
Same thing happens if you changed line 6 to "puts butt.get_contrib_count("xbony2", false)" or removed it entirely.

**Comment by elifoster** [comment]
Running Ruby 2.2.3p173, I do not get this warning. Try updating your version of Ruby.

**Comment by elifoster** [comment]
I just looked into it. [Refinements are no longer experimental as of Ruby 2.1](https://www.ruby-lang.org/en/news/2013/09/23/ruby-2-1-0-preview1-is-released/)

**Comment by xbony2** [comment]
Shouldn't we be using ruby 2.0, or at least not lying about it in the gemspec?

**Comment by elifoster** [comment]
That was written before I was using 2.3, on my old laptop. I didn't write the using stuff until I got my new laptop, which had ruby 2.3 installed default.
